apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: examples/simple
    repoURL: https://github.com/fcosta-td/argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
